"""Render and split the supported Telegram HTML subset without broken entities/tags."""
from __future__ import annotations

import html
from dataclasses import dataclass
from html.parser import HTMLParser


def escape(value: object) -> str:
    """Escape untrusted text, never use it as HTML markup."""
    return html.escape(str(value), quote=False)


def utf16_length(value: str) -> int:
    """Conservative Telegram text budget, including non-BMP Unicode characters."""
    return len(value.encode('utf-16-le')) // 2


@dataclass(frozen=True)
class Character:
    """A visible character and the markup stack that applies to it."""
    text: str
    stack: tuple[tuple[str, str], ...]


class _Parser(HTMLParser):
    """Validate the small HTML subset generated by this application."""
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[tuple[str, str]] = []
        self.characters: list[Character] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag not in {'b', 'i', 'code', 'blockquote', 'a'}:
            raise ValueError(f'Unsupported Telegram HTML tag: {tag}')
        if tag == 'a':
            values = dict(attrs)
            href = values.get('href', '') or ''
            if len(attrs) != 1 or not href.startswith(('https://', 'http://')):
                raise ValueError('Only HTTP(S) source links are allowed')
            opening = f'<a href="{html.escape(href, quote=True)}">'
        else:
            if attrs:
                raise ValueError(f'Unexpected attributes on {tag}')
            opening = f'<{tag}>'
        self.stack.append((tag, opening))
        if len(self.stack) > 8:
            raise ValueError('HTML nesting is too deep')

    def handle_endtag(self, tag: str) -> None:
        if not self.stack or self.stack[-1][0] != tag:
            raise ValueError(f'Unbalanced HTML closing tag: {tag}')
        self.stack.pop()

    def handle_data(self, data: str) -> None:
        self.characters.extend(Character(c, tuple(self.stack)) for c in data)

    def handle_comment(self, data: str) -> None:
        raise ValueError('HTML comments are not supported')

    def handle_decl(self, decl: str) -> None:
        raise ValueError('HTML declarations are not supported')


def _characters(text: str) -> list[Character]:
    parser = _Parser()
    parser.feed(text)
    parser.close()
    if parser.stack:
        raise ValueError('Unclosed HTML tags')
    return parser.characters


def plain_text(text: str) -> str:
    """Return visible text, validating the generated HTML along the way."""
    return ''.join(item.text for item in _characters(text))


def _render(characters: list[Character]) -> str:
    result: list[str] = []
    current: tuple[tuple[str, str], ...] = ()
    for item in characters:
        common = 0
        while common < min(len(current), len(item.stack)) and current[common] == item.stack[common]:
            common += 1
        result.extend(f'</{tag}>' for tag, _ in reversed(current[common:]))
        result.extend(opening for _, opening in item.stack[common:])
        result.append(escape(item.text))
        current = item.stack
    result.extend(f'</{tag}>' for tag, _ in reversed(current))
    return ''.join(result)


def split_message(text: str, limit: int = 3900) -> list[str]:
    """Split by visible UTF-16 units, reopening formatting safely in every chunk.

    Whitespace at a chunk boundary is removed; verse words, entities and Unicode
    code points are never cut or dropped. Generated HTML must be well formed.
    """
    if not 100 <= limit <= 4096:
        raise ValueError('limit must be between 100 and 4096')
    characters = _characters(text.strip())
    chunks: list[str] = []
    start = 0
    while start < len(characters):
        while start < len(characters) and characters[start].text.isspace():
            start += 1
        end, size, boundary = start, 0, None
        while end < len(characters):
            units = utf16_length(characters[end].text)
            if size + units > limit:
                break
            size += units
            if size >= limit // 2 and characters[end].text.isspace():
                boundary = end
            end += 1
        if end < len(characters) and boundary is not None:
            end = boundary
        stop = end
        while stop > start and characters[stop - 1].text.isspace():
            stop -= 1
        if stop > start:
            chunks.append(_render(characters[start:stop]))
        start = max(end, start + 1)
    return chunks
